# Generated by Django 3.2.11 on 2022-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='', upload_to='images/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('caption', models.TextField()),
            ],
        ),
    ]
