# Generated by Django 3.2.11 on 2022-01-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_friends_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
