# Generated by Django 3.2.11 on 2022-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank='True', default='images/default.jpg', upload_to='images/'),
        ),
    ]
