# Generated by Django 3.2.11 on 2022-01-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
